spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path
  datasource:
    url: jdbc:h2:mem:test     # (2) JDBC URL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
